image: docker:latest

services:
  - name: docker:dind
    # command: ['--insecure-registry=docker-registry.infrastructure.svc.cluster.local:5000']
    # command: ['--insecure-registry=registry.ci.com']

stages:
  - build
  - release

variables:
  DOCKER_HOST: unix:///var/run/docker.sock
  DOCKER_TLS_CERTDIR: ""
  GIT_SUBMODULE_STRATEGY: recursive
  CI_REGISTRY_USER: AWS
  # CI_REGISTRY_PASSWORD: ''
  CI_REGISTRY: ${CI_REGISTRY}
  CI_REGISTRY_IMAGE: ${CI_REGISTRY}/${CI_REGISTRY_NAME}
  BUILD_IMAGE: ${CI_REGISTRY}/${CI_REGISTRY_NAME}:build-${CI_COMMIT_SHORT_SHA}
  RELEASE_IMAGE: ${CI_REGISTRY}/${CI_REGISTRY_NAME}:${CI_COMMIT_REF_SLUG}
  SHA_IMAGE: ${CI_REGISTRY}/${CI_REGISTRY_NAME}:${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}
  TAG_IMAGE: ${CI_REGISTRY}/${CI_REGISTRY_NAME}:${CI_COMMIT_TAG}
  AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}

build:
  stage: build
  script:
    - echo "🦄️ $CI_REGISTRY_IMAGE"
    - echo "🦄️ Build:$BUILD_IMAGE"
    - echo "🦄️ Release:$RELEASE_IMAGE"
    - echo "🦄️ Commit:$SHA_IMAGE"
    - sh -c '[[ -n "$CI_COMMIT_TAG" ]] && echo "tag:$TAG_IMAGE" || echo "no tag found."'
    #    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build --cache-from "$RELEASE_IMAGE" --pull -t "$BUILD_IMAGE" -f Dockerfile .
    # - docker run "$BUILD_IMAGE" yarn test
    # - docker push "$BUILD_IMAGE"
#   except:
#     - tags

release:
  stage: release
  before_script:
    - apk add --no-cache curl py-pip
    - pip install awscli
  script:
    - aws ecr get-login-password --region ap-northeast-1 | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    # - docker pull "$BUILD_IMAGE" | true
    - echo "🦄️ Build Image:$BUILD_IMAGE"
    - echo "🦄️ Release:$RELEASE_IMAGE"
    - echo "🦄️ Commit:$SHA_IMAGE"
    - docker tag "$BUILD_IMAGE" "$RELEASE_IMAGE"
    - docker tag "$BUILD_IMAGE" "$SHA_IMAGE"
    - docker tag "$BUILD_IMAGE" "$CI_REGISTRY_IMAGE:latest"
    - |
      if [[ -n "$CI_COMMIT_TAG" ]]; then
        SUFFIX=`[[ "$CI_COMMIT_REF_SLUG" -ne "master" ]] && echo -n "-dev" || echo -n ""`
        docker tag "$BUILD_IMAGE" "$TAG_IMAGE$SUFFIX"
        echo "🦄️ deploy tag $TAG_IMAGE$SUFFIX ..."
        docker push "$TAG_IMAGE$SUFFIX"
      else
        docker rmi "$BUILD_IMAGE"
        echo "️🦄️ deploy $CI_REGISTRY_IMAGE ..."
        docker push "$RELEASE_IMAGE"
        docker push "$SHA_IMAGE"
      fi
  only:
    - master
    - develop
    - tags
